# This file contains the Scientist Path

class ScientistPath:
        def __init__(self):
                self.name = 'Scientist

# The Scientist story line
def scientist():
        print('XXXXXXXXXXXXXXXXXXXXXXXXX')
        print('XX THE TRUE METHOND XXXXX')
        print('XXXXXXXXXXXXXXXXXXXXXXXXX')
        print('XXXX OF KNOWLEDGE XXXXXXX')
        print('XXXXXXXXXXXXXXXXXXXXXXXXX')
        print('XXXX EXPERIMENT XXXXXXXXX')
        print('XXXXXXXXXXXXXXXXXXXXXXXXX')
        print()
        print('You are Alexandra')
        print('        the Scientest')
        print('        whose curse & blessing is the Truth')
        print()
        print('There is no more life. Only the sands move in the Land of Death.')
        print()
        print('But there is hope:')
        print('       where this tomb')
        print('       is hidden the seed')
        print('       of the TREE OF LIFE')
        print()
        print('The hazy ghost of Weariness is always upon you, breaking your will.')
        print('You fear that tyou may fail before the Great Work is finished.')
        print()
        #dialog(1, 'Seek The Seed of Life')
        print()
        print('      XX')
        #time.sleep(.2)
        print('    XXXXXX')
        #time.sleep(.2)
        print('  XXXXXXXXXX')
        #time.sleep(.2)
        print('XXXXXXXXXXXXXX')
        #time.sleep(.2)
        print()
        print('NONE WHO DESCEND INTO THIS TOMB SHALL RETURN')
        print()
        dialog(1,'ENTER THE TOMB')
        print()
        print('XXXXXXX Stairs lead down')
        print('XXXXXXXXXXXXXXX to the dark chambers')
        print('XXXXXXXXXXXXXXXXXXXXXXX in the heart of the Earth')
        print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX where the Seed awaits the Light')
        print()
        dialog(1, "Enter the Sage's Chamber")
        dialog(2,'Descend')
        ans = int(input('?: '))
        if ans == 1:
                print()
                print('The ghost of the Ancien Sage speaks.')
                print()
                print('I have beheld the wonders of the cosomos:')
                print('                          the fire of a million suns')
                print('                          the wind amoungst the starts')
                print('                          the black silence between the worlds')
                print('and now my heart is full o9f fear')
                print('for I know:')
                print('           the world was not made for us.')
                print()
                dialog(1, Descend)
                input('Decend?: ')
        return 3
